// <auto-generated />
namespace SpaceBlackMarket.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FirstSeededOutpost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstSeededOutpost));
        
        string IMigrationMetadata.Id
        {
            get { return "202202060540071_FirstSeededOutpost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
